### ISSUE TITLE
input의 날짜폴더 안쪽에서 실행할 수있도록 수정

### ISSUE THREAD

**Issue by jyub86** [75mm-studio/iomanager#3]

**Comment by kohyuk91** [comment]
```
[hko@localhost plate]$ pwd
/storage/show/rasca_190720_panda/input/190721/plate
- DATE폴더 하위에 있는 plate폴더에서 iom -v를 실행했더니 애러가 발생합니다.
```

```
<RESULT>
[hko@localhost plate]$ iom -v
Searching sequences...
File analyzing...
- Progress |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100.0%  Complete 00:00:00
Traceback (most recent call last):
  File "/storage/INHOUSE/apps/iomanager/iomanager.py", line 497, in <module>
    main()
  File "/storage/INHOUSE/apps/iomanager/iomanager.py", line 471, in main
    err = csvTask(path, dateFolder)
  File "/storage/INHOUSE/apps/iomanager/iomanager.py", line 134, in csvTask
    errList = checkData(csvFile, dateFolder)
  File "/storage/INHOUSE/apps/iomanager/iomanager.py", line 202, in checkData
    prjData = importCSV(prjCsvFile)
  File "/storage/INHOUSE/apps/iomanager/iomanager.py", line 233, in importCSV
    with open(csvFile, "r") as f:
IOError: [Errno 2] No such file or directory: '/storage/show/rasca_190720_panda/input/data.csv'
```

**Comment by kohyuk91** [comment]
```
현재
/storage/show/rasca_190720_panda/input/190721/scans/S01/0010/C02.%04d.jpg
/storage/show/rasca_190720_panda/scenes/**scans**/S01/0010/plate/jpg
```

```
요청 - DATE폴더와 샷 사이에 있는 폴더들을 trim.

ex1)
Input Path - /storage/show/rasca_190720_panda/input/190721/scans/S01/0010/S01_0010.%04d.jpg
[hko@localhost scans]$ iom -v
Plate Path - /storage/show/rasca_190720_panda/scenes/S01/0010/plate/jpg

ex2)
Input Path - /storage/show/rasca_190720_panda/input/190721/scans/footage/S01/0010/S01_0010.%04d.jpg
[hko@localhost footage]$ iom -v
Plate Path - /storage/show/rasca_190720_panda/scenes/S01/0010/plate/jpg
```

**Comment by jyub86** [comment]
update
